apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: vida-prod
  name: demo-nginx-site-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: demo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-nginx-site-service
            port:
              number: 8080
