apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vida-ui-application
  namespace: argocd

spec: 
  project: vida-prod

  source:
    repoURL: 'https://github.com/VinulVinsura/VIDA-Hospital.git'
    targetRevision: main            # Git branch, tag, or commit SHA
    path: PROD                 # Folder in repo with K8s YAMLs or Helm chart

  destination:
    server: 'https://kubernetes.default.svc'  # Or use specific cluster URL
    namespace: vida-prod             # Namespace to deploy into

  syncPolicy:
    automated:                     # Enables auto-sync
      selfHeal: true               # Automatically fix out-of-sync resources
